### ISSUE TITLE
Icons showing incorrectly for custom created activities/rewards

### ISSUE THREAD

**Issue by pkvanbeck** [EveningMoon/Balance#9]
When an activity or reward is added it shows correctly with the first letter of its name in the list view. Once that custom option reaches the top three section on either the earn or burn panel on the main page the letter in the icon location is always defaulted to "J" 

On the Transaction screen the icon for a custom added activity or reward will show up correctly on its first use and then grab random icons after that.

![screenshot_20160603-103917](https://cloud.githubusercontent.com/assets/7718177/15787519/c3f22dac-2977-11e6-945b-74903cad4cb6.png)
![screenshot_20160603-103922](https://cloud.githubusercontent.com/assets/7718177/15787517/c3efdeee-2977-11e6-8407-bba90557e4ff.png)
![screenshot_20160603-103850](https://cloud.githubusercontent.com/assets/7718177/15787518/c3f0c3ae-2977-11e6-8e69-c194194c00d3.png)

**Comment by zhanhui913** [comment]
done
